// Generated by CoffeeScript 1.4.0

/**
 * jsonTable.coffee v0.1
 *
 * 1337@github
 *
 * MIT
 *
 * Written in CoffeeScript because I want actual classes. Sue me.
*/


(function() {
  "use strict";

  var HTMLElement, TableBody, TableData, TableElement, TableHead, TableHeader, TableRow, _base, _ref, _ref1,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  HTMLElement = (function() {
    /**
     * Manipulatable, self-closing "element" object.
    */

    HTMLElement.prototype.tagName = 'div';

    HTMLElement.prototype.className = '';

    HTMLElement.prototype.style = '';

    HTMLElement.prototype.children = [];

    function HTMLElement(params) {
      this.toString = __bind(this.toString, this);

      var thing, _i, _len;
      for (_i = 0, _len = params.length; _i < _len; _i++) {
        thing = params[_i];
        this.add(thing);
      }
    }

    HTMLElement.prototype.add = function(child) {
      return this.children.push(child);
    };

    HTMLElement.prototype.toString = function() {
      var child;
      return "<" + this.tagName + " class=\"" + this.className + "\" style=\"" + this.style + "\">\n  " + ((function() {
        var _i, _len, _ref, _results;
        _ref = this.children;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          child = _ref[_i];
          _results.push(this.child.toString());
        }
        return _results;
      }).call(this)) + "\n</" + this.tagName + ">";
    };

    return HTMLElement;

  })();

  TableElement = (function(_super) {

    __extends(TableElement, _super);

    function TableElement() {
      return TableElement.__super__.constructor.apply(this, arguments);
    }

    TableElement.prototype.tagName = 'table';

    return TableElement;

  })(HTMLElement);

  TableHead = (function(_super) {

    __extends(TableHead, _super);

    function TableHead() {
      return TableHead.__super__.constructor.apply(this, arguments);
    }

    TableHead.prototype.tagName = 'thead';

    return TableHead;

  })(HTMLElement);

  TableBody = (function(_super) {

    __extends(TableBody, _super);

    function TableBody() {
      return TableBody.__super__.constructor.apply(this, arguments);
    }

    TableBody.prototype.tagName = 'thead';

    return TableBody;

  })(HTMLElement);

  TableData = (function(_super) {

    __extends(TableData, _super);

    function TableData() {
      return TableData.__super__.constructor.apply(this, arguments);
    }

    TableData.prototype.tagName = 'td';

    return TableData;

  })(HTMLElement);

  TableRow = (function(_super) {

    __extends(TableRow, _super);

    function TableRow() {
      return TableRow.__super__.constructor.apply(this, arguments);
    }

    TableRow.prototype.tagName = 'tr';

    return TableRow;

  })(HTMLElement);

  TableHeader = (function(_super) {

    __extends(TableHeader, _super);

    function TableHeader() {
      return TableHeader.__super__.constructor.apply(this, arguments);
    }

    TableHeader.prototype.tagName = 'th';

    return TableHeader;

  })(TableData);

  if ((_ref = window.ca) == null) {
    window.ca = {};
  }

  if ((_ref1 = (_base = window.ca).ohai) == null) {
    _base.ohai = {};
  }

  window.ca.ohai.jsonTable = function(json) {
    var row, table, _i, _len, _results;
    table = new TableElement;
    _results = [];
    for (_i = 0, _len = json.length; _i < _len; _i++) {
      row = json[_i];
      _results.push(table.add(new TableRow(row)));
    }
    return _results;
  };

}).call(this);
